# 리스트 만들기

크기 N의 1차원 배열 : Arr = [Initial_Data]*N

N*N 2차원 배열 : Matrix = [[Initial_Data]*N for _ in range(N)]

N*M 2차원 배열 : Matrix = [[Initial_Data]*M for _ in range(N)]

In [60]:
my2list = [0] * 3
my2list

[0, 0, 0]

In [61]:
my2list.append(1)
my2list

[0, 0, 0, 1]

# Numpy

In [4]:
import numpy as np

mylist = [1, 2, 3]
myarray = np.array(mylist)      # Array로 변환

type(mylist)         # <class 'list'>

list

In [3]:
type(myarray)        # <class 'numpy.ndarray'>

numpy.ndarray

In [5]:
# 배열 모양 확인
myarray.shape        # (3,)   ←  행, 열 (1, 3)

(3,)

In [6]:
# 배열에 들어있는 자료형 확인
myarray.dtype        # int32

dtype('int32')

In [7]:
# 자료형 지정
myarray3 = np.array([1, 2, 3], dtype=np.int8)
myarray3.dtype       # int8

dtype('int8')

In [8]:
# 자료형 변경
myarray.astype(np.int8)
myarray.dtype        # int32

dtype('int32')

# Numpy array init : 넘파이 어레이 초기화

1) Zeros

In [10]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
np.zeros((3,5)).shape         # 행, 열 (3, 5)

(3, 5)

2) Ones

In [13]:
np.ones(9)

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [14]:
np.ones((2,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [15]:
np.ones((2,10)).shape          # 행, 열 (2, 10)

(2, 10)

3) Arrange

In [16]:
np.arange(10)            # [0 1 2 3 4 5 6 7 8 9]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.arange(3, 10)         # [3 4 5 6 7 8 9]

array([3, 4, 5, 6, 7, 8, 9])

4) full

In [18]:
np.full(10, 3.14)

array([3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14])

# Numpy indexing

In [24]:
arr1 = np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
# 0번째 요소
arr1[0]

0

In [26]:
# 3번째 요소
arr1[3]

3

# 슬라이싱 하기

In [27]:
# 3번째 요소 부터 8번째 요소
arr1[3:9]

array([3, 4, 5, 6, 7, 8])

In [28]:
# 모든 데이터 가져오기
arr1[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
# 간격을 주고 가져오기
arr1[0:5:2]

array([0, 2, 4])

In [30]:
# 2차원 배열 슬라이싱 하기
arr2d = np.arange(25).reshape(5,5)
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [31]:
arr2d[1:3, :]

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

# Numpy random
np.random.rand : 0~1 사이의 랜덤값, 균일분포 표준정규분포 난수

In [32]:
np.random.rand(6)

array([0.51544395, 0.39779958, 0.06919409, 0.28125224, 0.6418297 ,
       0.44354207])

In [33]:
np.random.rand(3,2)

array([[0.31547383, 0.29526314],
       [0.98286112, 0.74859377],
       [0.5782475 , 0.07776337]])

np.random.randint : int 난수

In [34]:
np.random.randint(6)        # 0 or 1 or ~ or 5     0부터 5까지 랜덤한 숫자 1개

3

In [35]:
np.random.randint(1, 20)        # 1부터 19까지 랜덤한 숫자 1개

7

np.random.uniform, random.normal, random.randn : 다양한 분포에서 생성 가능

np.random.seed(N) : 언제나 같은 값의 난수 값을 얻기 위해 사용

# Numpy 연산

In [36]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [37]:
arr1.shape

(2, 3)

In [38]:
arr2 = np.array([[10, 11, 12], [13, 14, 15]])
arr2

array([[10, 11, 12],
       [13, 14, 15]])

In [39]:
arr2.shape

(2, 3)

각 요소별 위치에서 연산 진행

In [40]:
arr1 + arr2

array([[11, 13, 15],
       [17, 19, 21]])

In [41]:
arr1 - arr2

array([[-9, -9, -9],
       [-9, -9, -9]])

In [42]:
arr1 * arr2

array([[10, 22, 36],
       [52, 70, 90]])

In [43]:
arr1 / arr2

array([[0.1       , 0.18181818, 0.25      ],
       [0.30769231, 0.35714286, 0.4       ]])

Numpy array 연산(axis 개념)

In [45]:
# 전체 성분의 합을 계산
np.sum(arr1)

21

In [46]:
# 열 간의 합을 계산
np.sum(arr1, axis=1)

array([ 6, 15])

In [47]:
# 행 간의 합을 계산
np.sum(arr1, axis=0)

array([5, 7, 9])

# Numpy reshape
'같은' size의 다른 데이터 형태로 변형하기 -> np.reshape

기본적으로 가로 정렬이다.

세로로 정렬하려면 order = 'F' 옵션 추가

In [51]:
arr3 = np.zeros((3,4,5))
arr3

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [52]:
arr3.shape

(3, 4, 5)

In [53]:
arr3.reshape(5, -1)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [54]:
arr3.reshape(2, 6, -1)

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [55]:
arr3.reshape(-1)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0.])

# Numpy flatten, transpose
np.reshape(-1), np.ravel(), np.flatten() -> 1차원 벡터로 변경

*flatten의 경우 기존 객체 변경하지 않음

In [57]:
arr4 = np.zeros((5, 6))
arr4.reshape(-1)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [58]:
# reshape를 하여도 기존 array에는 영향주지 않는다.
arr4

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

np.transpose(arr), arr.T -> 행 열 변경(transpose)

In [59]:
arr4.T

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])